### ISSUE TITLE
Release it

### ISSUE THREAD

**Issue by defunkt** [mojombo/tomdoc#1]

**Comment by kneath** [comment]
+1

**Comment by rtomayko** [comment]
+1

**Comment by cmaxw** [comment]
+1

**Comment by mojombo** [comment]
Fixed!

**Comment by cmaxw** [comment]
I don't see the code in the repository

**Comment by mojombo** [comment]
@charlesmaxwood This repo contains the spec only. @defunkt is working on a gem that will format TomDoc'd code for the terminal or HTML though: http://github.com/defunkt/tomdoc.

**Comment by cmaxw** [comment]
SWEET!
