### ISSUE TITLE
Is "Examples" keyword really needed?

### ISSUE THREAD

**Issue by ghost** [mojombo/tomdoc#10]
Can't everything after the list of parameters and before the final Returns phrase be considered "examples and notes" --so it can be more free form. There are times when complex explanations are needed including things like tables of information. This would seem to be the place for it, but it's isn't an "example".

**Comment by trans** [comment]
On further thought, perhaps an optional alternative layout could also be used, whereby the Interface is the thing specifically stated.

```
# Does something or another.
#
#   something("foo")
#
# Interface
#
# arg - argument with which to do something
#
# Returns some Object.
def something(arg)
   # ...
end
```

So the examples are really just part of the description. One can put "Examples" if they want of course.

**Comment by mojombo** [comment]
I like having an explicity examples section. It encourages people to actually include a few of them. For everything else, that should all go in the description section, even if it ends up long. I'll add a bit to the description spec to make sure people know you can be as freeform as you like (paragraphs, code, tables, whatever).
