### ISSUE TITLE
Gem::LoadError for RubyInline 

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#18]
Gem::LoadError: can't activate RubyInline (= 3.7.0, runtime) for ["tomdoc-0.1.0"], already activated RubyInline-3.9.0 for ["ParseTree-3.0.5", "tomdoc-0.1.0"]

**Comment by mojombo** [comment]
This repo is just the TomDoc spec. I think you're looking for defunkt/tomdoc.

**Comment by trans** [comment]
Right you are!
