### ISSUE TITLE
Using blank lines to separate examples may result in ambiguity

### ISSUE THREAD

**Issue by rgrove** [mojombo/tomdoc#2]
From The Examples Section: "Separate examples should be separated by a blank line."

What about individual examples that contain vertical whitespace for readability? If a doc generation tool were to assume that each blank line denotes the beginning of a new example, this could result in undesired formatting.

**Comment by mojombo** [comment]
I'd say that the examples section should just be formatted as one big chunk, regardless of how many examples it contains. You can just use comments to say where the multi-section examples start and end.

**Comment by rgrove** [comment]
That sounds reasonable. In that case, simply removing that sentence should resolve any ambiguity as to whether a parser is expected to denote separate examples or just treat the whole thing as one big chunk.
