### ISSUE TITLE
Section Order

### ISSUE THREAD

**Issue by drbrain** [mojombo/tomdoc#25]
Must the sections be given in exactly the order presented?  The spec is not clear on if the Signatures section MUST come after a Returns section, etc.

**Comment by sarahhodne** [comment]
As far as I can see, the order of the sections isn't explicitly specified at all. I would do it in the order they are listed in the spec unless you have a (good?) reason to do otherwise.

**Comment by sarahhodne** [comment]
Also, issue #21 talks about where the Signatures section is put in the spec.
