### ISSUE TITLE
Use Markdown for simple markup

### ISSUE THREAD

**Issue by dasch** [mojombo/tomdoc#33]
Having a way to denote inline code blocks, adding emphasis to words and paragraphs, adding external links, and arbitrary lists would be really nice.

I think Markdown is the perfect fit for TomDoc, as it builds on the same principle (readability as plaintext,) while allowing for machine parsing.

**Comment by mojombo** [comment]
I think Markdown is way overkill for TomDoc. About the only thing I could be convinced to include is a syntax for inline code using backticks. Of course, you can just use those right now if you please.

**Comment by dasch** [comment]
Inline backticks would probably suffice for most purposes, although I do use lists extensively, and feel that they're valuable in documentation.

**Comment by mojombo** [comment]
> I do use lists extensively, and feel that they're valuable in documentation.

Sure, lists are great. They show up nicely in plaintext too, though, so I don't see it as a huge issue.

**Comment by dasch** [comment]
I guess I have to accept that TomDoc is only meant to be displayed verbatim :-)
