### ISSUE TITLE
Confusion about optional options

### ISSUE THREAD

**Issue by dasch** [mojombo/tomdoc#37]
The specification states that:

> If an argument is optional, you MUST specify the default value.

And continues to display an examples where the `(default: "...")` syntax is used to denote the default value. In the next paragraph:

> For hash arguments, you SHOULD enumerate each valid option in a way similar to how normal arguments are defined.

Yet these use a completely different syntax to denote optional arguments/options, appending `(optional)` to the descriptions.

Why this discrepancy? I would find it easier to read and write TomDoc if these two forms were identical, differing only in the way the arguments were passed (named/positional).

I suggest either allowing both syntaxes or only one, but have it be the same for normal arguments and the options hash items.

**Comment by mojombo** [comment]
The spec is purposefully vague about hash options since people use them in many different ways. Most of the time the options are truly optional and have no default. If they do, it's wise to state the default. Do whatever makes the documentation most clear.

**Comment by dasch** [comment]
Okay, thanks.
