### ISSUE TITLE
Indented arguments

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#40]
Can indented arguments be an accepted format, to me it reads better, e.g.

``` ruby
# Public: Duplicate some text an arbitrary number of times.
#
#   text  - The String to be duplicated.
#   count - The Integer number of times to duplicate the text.
#
# Examples
#
#   multiplex('Tom', 4)
#   # => 'TomTomTomTom'
#
# Returns the duplicated String.
def multiplex(text, count)
  text * count
end
```

**Comment by mojombo** [comment]
I don't think this adds enough clarity to warrant extra typing. I've never been bothered by it, at least.

**Comment by trans** [comment]
Any reason for it not to be an option?

**Comment by sarahhodne** [comment]
To me, this makes it looks like the arguments are a part of the description section, when it is in fact its own section.

**Comment by trans** [comment]
Interesting b/c I tend to feel like the non-indented form makes it seems part of the description. But I can see it from your point of view too. I wonder if an `Arguments` section label would be better.

``` ruby
# Public: Duplicate some text an arbitrary number of times.
#
# Arguments
#
#   text  - The String to be duplicated.
#   count - The Integer number of times to duplicate the text.
#
# Examples
#
#   multiplex('Tom', 4)
#   # => 'TomTomTomTom'
#
# Returns the duplicated String.
```

**Comment by trans** [comment]
Honestly, coming back to this after so many months, I find my last example so much more readable. It may take up more space, but its dead easy it mentally parse.

I don't see any show-stopping reason this couldn't be supported along side the current design?
