### ISSUE TITLE
Any Markup Support

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#5]
Does TomDoc support any markup at all? Bold, italic, hyperlinks, etc? While I fully understand the goal of readable plan text, at the same time we want to produce even nicer production output. There must be a reasonable middle ground.

**Comment by defunkt** [comment]
Use whatever markup you want. TomDoc isn't RDoc and shouldn't put that kind of stuff into the spec.

For my [tomdoc generator](http://github.com/defunkt/tomdoc) I'd like to eventually support whatever - Markdown, Textile, RDoc, anything. 

I love that TomDoc is so syntactically sparse that swapping out markups is possible.

**Comment by mojombo** [comment]
I personally don't much care to put markup in my docs and I don't think TomDoc should take a stance. Like Chris said, if formatters want to respect various markups then that's their choice. I'd encourage writing in a plain way that doesn't require a lot of fancy formatting over cluttering things with a ton of markup.

**Comment by trans** [comment]
I agree. But light markup like ~italic~, _bold_, _underline_, +code+ and link[http://...] can be pretty useful.

So if TomDoc is formatter neutral how does one apply a custom formatter?

**Comment by anibali** [comment]
For readability of plain text documentation I prefer using backticks for code/commands. Using + or @ doesn't quite seem to hold much meaning for human readers... I suppose it's just a matter of opinion, though.
