### ISSUE TITLE
TomDoc for CoffeeScript?

### ISSUE THREAD

**Issue by johnnyshields** [mojombo/tomdoc#50]
Hi, TomDoc is great, the only thing I want is more of it!

These days it seems a CoffeeScript is gradually occupying more space in Rails apps, esp. with frameworks like Ember.js on the rise. It would be great if we could have a TomDoc analogue for CoffeeScript so our docs can be mostly-consistent<sup>TM</sup> across the repo.

**Comment by trans** [comment]
Would anything about the specification have to change? If not, then its just a matter of someone building an implementation. Are there any Coffeescript documentation tools out there now? If so, how do they work, and can TomDoc be a plugin for them?

**Comment by johnnyshields** [comment]
Maybe not... it's virtually the same. Forgot why I raised this originally. Maybe was meaning to get a CoffeeScript based parser or something. Hmmm.
