### ISSUE TITLE
ri tool

### ISSUE THREAD

**Issue by trans** [mojombo/tomdoc#8]
And what about ri? Does TomDoc provide anything along these lines, or are we still using rdoc for that?

**Comment by defunkt** [comment]
I'd like to add an ri generator to my [tomdoc](http://github.com/defunkt/tomdoc) library. I use ri a lot and it'd be a shame to lose that tool.

**Comment by mojombo** [comment]
Agreed. There's no reason that TomDoc couldn't be hooked up to ri. Just needs some code.

**Comment by trans** [comment]
How does TomDoc store the information internally? It might be better/easier to create a ri like tool for TomDoc.

**Comment by ghost** [comment]
What I would like to do is take Tomdoc's internal model and export it to a structured sqlite database. Then it would be easy to use that database to render various views of the documentation on the fly.
